version: '3.8'

# Quarkus Backend Configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.quarkus.yml up

services:
  # Nginx API Gateway for Quarkus
  nginx-api-quarkus:
    image: nginx:alpine
    container_name: restaurant-nginx-api-quarkus
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx-api-quarkus.conf:/etc/nginx/nginx.conf:ro
    networks:
      - restaurant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Quarkus Instance 1
  quarkus-app-1:
    build:
      context: ../backend/quarkus-app
      dockerfile: Dockerfile
    container_name: quarkus-app-1
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/restaurant_db
      QUARKUS_DATASOURCE_USERNAME: restaurant_user
      QUARKUS_DATASOURCE_PASSWORD: restaurant123
      QUARKUS_REDIS_HOSTS: redis:6379
      QUARKUS_HTTP_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - restaurant-network
    restart: unless-stopped

  # Quarkus Instance 2
  quarkus-app-2:
    build:
      context: ../backend/quarkus-app
      dockerfile: Dockerfile
    container_name: quarkus-app-2
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/restaurant_db
      QUARKUS_DATASOURCE_USERNAME: restaurant_user
      QUARKUS_DATASOURCE_PASSWORD: restaurant123
      QUARKUS_REDIS_HOSTS: redis:6379
      QUARKUS_HTTP_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - restaurant-network
    restart: unless-stopped
